resource_group_name      = "BCA-Hailstone-Dev"
location                 = "South UK"
az_function_name         = "bca-az-function-dev"
app_service_plan_name     = "bca-function-app-service-plan-dev"
storage_account_name      = "bca-storage-account-dev"