resource_group_name      = "BCA-Hailstone-Prod"
location                 = "South UK"
az_function_name         = "bca-az-function-prod"
app_service_plan_name     = "bca-function-app-service-plan-prod"
storage_account_name      = "bca-storage-account-prod"