resource_group_name      = "BCA-Hailstone-Test"
location                 = "South UK"
az_function_name         = "bca-az-function-test"
app_service_plan_name     = "bca-function-app-service-plan-test"
storage_account_name      = "bca-storage-account-test"