on:
  push:
    branches:
    - dev
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          
      - name: Debug
        run: |
          echo 'Current working directory:'
          pwd
          echo 'Contents of the current directory:'
          ls -R
          echo 'Going back one directory:'
          cd ..
          pwd
          echo 'Contents of the parent directory:'
          ls -R

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: python hailstone_unit_tests.py
  
