name: Test Env Push Dockerized app to ACR

on:
  push:
    branches:
    - test
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    env:
      DOCKER_IMAGE_NAME: hailstone-test
      ACR_NAME: bca_acr_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Lint Tests
        run: python Tests/lint_test.py

      - name: Run Unit Tests
        run: python Tests/hailstone_unit_tests.py

      - name: Build Docker image
        run: |
          echo 'Starting the build process'
          docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ github.event_name }} .

        #THIS WILL FAIL AS I DO NOT HAVE AN ACR SET UP
      - name: Push Docker image to Azure Container Registry
        run: |
          echo 'Starting the push process'
          docker login -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }} ${{ env.ACR_NAME }}.azurecr.io
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME }}:${{ github.event_name }}
          
      - name: Cleanup
        run: echo 'Build, test, and push process completed successfully'
