on:
  push:
    branches:
    - dev
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: python Tests/hailstone_unit_tests.py
        continue-on-error: true

      - name: Check Unit Test Results
        run: exit $(test -f test-results.xml && grep -c '<failure' test-results.xml)

  
